swagger: "2.0"
info:
  description: "API specification for the SmartLogic Concordance Transformer"
  
  version: "1.0.0"
  title: "SmartLogic Concordance Transformer"
host: pub-prod-up.ft.com
schemes:
  - https
basePath: /__smartlogic-concordance-transformer

paths:
  /transform:
    post:
      summary: Transform a Smart Logic representation of identifiers to an UPP concordance representation
      description: Transforms smartlogic payload into the upp representation of concordance if one exists and returns request. Used for support and testing
      tags:
        - Internal API
      consumes:
              - application/ld+json
      parameters:
        - name: transformRequest
          in: body
          description: Minimal Payload that comes out of the smartlogic api
          schema:
            type: string
          
      produces:
              - application/json
      responses:
        200:
          description: Returns the UPP representation of the concordances
          examples:
            application/json:
              - uuid: c372ffba-7a7f-11e6-aca9-d6ece9a77557
                concordedIds:
                  - authority: FT-TME
                    uuid: a931079b-00b8-4d10-b893-2b94ddd93b43
        400:
          description: Invalid input - invalid JSON-LD or a missing uuid
        405:
          description: Method not allowed - any method not specified for this endpoint will return a 405 response
        422:
          description: Unprocessable entity - request JSON-LD is unprocessable
        500:
          description: Internal error transforming the Smart Logic JSON-LD
        503:
          description: Service cannot connect to Kafka or the concordances-rw-dynamodb service
  /transform/send:
    post:
      summary: Transforms smartlogic payload into the upp representation of concordance and sends it to the concordance-rw-dynamodb. 
      description: Transforms smartlogic payload into the upp representation of concordance and sends it to the concordance-rw-dynamodb. If no concordance exists, a delete request is sent instead (response outlined in concordance-rw-dynamodb)
      tags:
        - Internal API
      produces:
        - application/json
      consumes:
              - application/ld+json
      parameters:
        - name: transformRequest
          in: body
          description: Minimal Payload that comes out of the smartlogic api
          schema:
            type: string  
      responses:
        200:
          description: Successfully transformed and sent onwards the concordance rw dynamodb
        400:
          description: Invalid input - invalid JSON-LD or a missing uuid
        405:
          description: Method not allowed - any method not specified for this endpoint will return a 405 response
        422:
          description: Unprocessable entity - request JSON-LD is unprocessable
        500:
          description: Internal error transforming the Smart Logic JSON-LD
        503:
          description: Service cannot connect to Kafka or the concordances-rw-dynamodb service
  
    
  /__ping:
    get:
      summary: Ping
      description: Returns "pong" if the server is running.
      produces:
        - text/plain; charset=utf-8
      tags:
        - Health
      responses:
        200:
          description: We return pong in plaintext only.
          examples:
            text/plain; charset=utf-8: pong
  /__health:
    get:
      summary: Healthchecks
      description: Runs application healthchecks and returns FT Healthcheck style json.
      produces:
        - application/json
      tags:
        - Health
      responses:
        200:
          description: Should always return 200 along with the output of the healthchecks - regardless of whether the healthchecks failed or not. Please inspect the overall `ok` property to see whether or not the application is healthy.
          examples:
            application/json:
              checks:
                - businessImpact: "No Business Impact."
                  checkOutput: "OK"
                  lastUpdated: "2017-01-16T10:26:47.222805121Z"
                  name: "Smart Logic Concordance Transformer Healthcheck"
                  ok: true
                  panicGuide: "https://dewey.ft.com/smartlogic-concordance-transformer.html"
                  severity: 1
                  technicalSummary: "TODO"
              description: TODO
              name: {{ cookiecutter.service_name }}
              ok: true
              schemaVersion: 1
  /__build-info:
    get:
      summary: Build Information
      description: Returns application build info, such as the git repository and revision, the golang version it was built with, and the app release version.
      produces:
       - application/json; charset=UTF-8
      tags:
        - Info
      responses:
        200:
          description: Outputs build information as described in the summary.
          examples:
            application/json; charset=UTF-8:
              version: "0.0.7"
              repository: "https://github.com/Financial-Times/smartlogic-concordance-transformer.git"
              revision: "7cdbdb18b4a518eef3ebb1b545fc124612f9d7cd"
              builder: "go version go1.6.3 linux/amd64"
              dateTime: "20161123122615"
  /__gtg:
    get:
      summary: Good To Go
      description: Lightly healthchecks the application, and returns a 200 if it's Good-To-Go.
      tags:
        - Health
      responses:
        200:
           description: The application is healthy enough to perform all its functions correctly - i.e. good to go.
        503:
           description: One or more of the applications healthchecks have failed, so please do not use the app. See the /__health endpoint for more detailed information.